### ISSUE TITLE
終了メニューの作成

### ISSUE THREAD

**Issue by hinshiba** [dice-2004/Union-Hack-2024#11]
メイン画面のときに ESC or ほかのキー で終了画面
- ゲームを続ける
- セーブせず終了
- セーブして終了

**Comment by dice-2004** [comment]
後者はメイン画面の上に終了メニューを重ねる的な感じですか？(ゲームでよくあるポーズみたいな)

**Comment by hinshiba** [comment]
その予定です

**Comment by hinshiba** [comment]
作成してもらっていいですか?

**Comment by dice-2004** [comment]
じゃあゲームのポーズ画面的なもの作っときます

**Comment by hinshiba** [comment]
ありがとうございます。
