### ISSUE TITLE
ファイルパス指定方法の見直し

### ISSUE THREAD

**Issue by hinshiba** [dice-2004/Union-Hack-2024#8]
面倒なのでdiscordより引用

Path(__file__).parents[1] とすることで実行場所にかかわらずUnion-Hack-2024/を指すと思うのでこうしましょうか?

**Comment by dice-2004** [comment]
いや、わざわざsrc内に入るのも面倒だったのでもう実行は python ./src/main.pyでするって決めといたらいいんじゃないですか？

**Comment by hinshiba** [comment]
そうですね
