### ISSUE TITLE
タイトルのフリーフォントをどれにするか

### ISSUE THREAD

**Issue by dice-2004** [dice-2004/Union-Hack-2024#9]
どれが合いそうとか意見あったら言ってください

**Comment by hinshiba** [comment]
x12y16pxMaruMonicaとかどうでしょうか
ドット調でタイルと会うのではないかと

以下配布場所
https://booth.pm/ja/items/2958237

以下Licence
https://hicchicc.github.io/00ff/

**Comment by dice-2004** [comment]
それでいきましょう。
追加しときます
